AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Upload Excel xlsx to S3 and trigger Excel Lex Bot
Parameters:
  DynamodbAutoScaling:
    Type: String
    Default: true
    AllowedValues:
    - true
    - false
    Description: Enable DynamoDB AutoScaling
Metadata:
  AWS::ServerlessRepo::Application:
    Name: ExcelLexBot
    Description: ExcelLexBot is a serverless application that converts an Excel file
      (xlsx) in predefined format into an Amazon Lex chatbot.
    Author: Cyrus Wong
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://excelbot-jy-east1/175792518e4ac015ab6696d16c4f607e
    ReadmeUrl: s3://excelbot-jy-east1/8d2ad0d2e6a045815c2243ffb29d0fd8
    Labels:
    - Lex
    HomePageUrl: https://github.com/wongcyrus/ExcelLexBot
    SemanticVersion: '0.0.2'
    SourceCodeUrl: https://github.com/wongcyrus/ExcelLexBot
Resources:
  ExcelLexBotS3TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create Lex Chat Bot when upload xlsx file.
      Handler: s3_trigger_handler.lambda_handler
      Runtime: python3.7
      MemorySize: 512
      Timeout: 300
      Tracing: Active
      Layers:
      - Ref: LibLayer
      Policies:
      - AWSXrayWriteOnlyAccess
      - AWSLambdaExecute
      - AmazonLexFullAccess
      - AmazonSNSFullAccess
      - AmazonDynamoDBFullAccess
      - AWSLambdaFullAccess
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:CreateStack
          - cloudformation:DescribeChangeSet
          - cloudformation:CreateChangeSet
          - cloudformation:DeleteChangeSet
          - cloudformation:DeleteStack
          - cloudformation:ExecuteChangeSet
          - cloudwatch:DescribeAlarms
          - cloudwatch:PutMetricAlarm
          - cloudwatch:DeleteAlarms
          - iam:CreateRole
          - iam:DeleteRole
          - iam:AttachRolePolicy
          - iam:DetachRolePolicy
          - iam:PutRolePolicy
          - iam:DeleteRolePolicy
          - iam:PassRole
          Resource: '*'
      Environment:
        Variables:
          DynamodbAutoScaling:
            Ref: DynamodbAutoScaling
          LibLayer:
            Ref: LibLayer
      CodeUri: s3://excelbot-jy-east1/15c5b0a0b7e178e06d786c6f1a969913
      Events:
        XlsxPut:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .xlsx
        XlsxDelete:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket
            Events: s3:ObjectRemoved:Delete
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .xlsx
  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://excelbot-jy-east1/9eac7ead7d7204cf0e5d011619e213a1
      CompatibleRuntimes:
      - python3.7
      LicenseInfo: Available under the MIT-0 license.
      RetentionPolicy: Delete
  Bucket:
    Type: AWS::S3::Bucket
Outputs:
  LexExcelBucket:
    Description: Lex Excel Bucket
    Value:
      Ref: Bucket
