AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'MIDS chatbot - class_per_term intent'
Resources:
  classperterm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        MIDS chatbot - class_per_term intent
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::098766315756:role/service-role/class_per_term-role-d8fq8nk9'
      Tags:
        'lambda-console:blueprint': lex-order-flowers-python
